{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vectorflow.gateway.fullname" . }}
  labels:
    {{- include "vectorflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - port: {{ .Values.gateway.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vectorflow.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
---
{{- end }}
{{- if .Values.worker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vectorflow.worker.fullname" . }}
  labels:
    {{- include "vectorflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  type: {{ .Values.worker.service.type }}
  ports:
    - port: {{ .Values.worker.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vectorflow.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: worker
---
{{- end }}
{{- if .Values.inference.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vectorflow.inference.fullname" . }}
  labels:
    {{- include "vectorflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: inference
spec:
  type: {{ .Values.inference.service.type }}
  ports:
    - port: {{ .Values.inference.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vectorflow.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: inference
---
{{- end }}
{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vectorflow.frontend.fullname" . }}
  labels:
    {{- include "vectorflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vectorflow.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
{{- end }}
